### ISSUE TITLE
Documentation link is 404

### ISSUE THREAD

**Issue by DmytroLitvinov** [dnmellen/dj-warning-forms#2]
Hi there,
[Documentation link](https://dj-warning-forms.readthedocs.io/) which is mentioned in README.rst file is broken (returns 404 page at readthedocs.io)

**Comment by dnmellen** [comment]
Hi! 

I'm trying to connect this project with readthedocs.io, but it's always returning me a 502 error whenever I link my GitHub account.

I will keep trying to build the docs, but anyway, you have all the relevant info in the README.rst.

Thanks!

**Comment by dnmellen** [comment]
Docs fixed!
